"""Public package surface for Evidpath."""

from .audit import execute_domain_audit
from .config import build_run_config
from .domain_registry import (
    get_domain_definition,
    list_domain_definitions,
    list_public_domain_definitions,
    register_domain_definition,
)
from .population_generation import generate_population_pack, load_population_pack
from .regression import run_domain_regression_audit, run_regression_audit
from .scenario_generation import generate_scenario_pack, load_scenario_pack
from .schema import (
    Action,
    ActionDecision,
    AdapterRequest,
    AdapterResponse,
    AgentSeed,
    AgentState,
    AnalysisResult,
    CohortSummary,
    DecisionExplanation,
    FailureMode,
    FailureModeCount,
    GeneratedPersona,
    GeneratedScenario,
    MetricDelta,
    MetricSummary,
    Observation,
    PopulationGeneratorMode,
    PopulationPack,
    PopulationPackMetadata,
    RankedItem,
    RankedList,
    RegressionDiff,
    RegressionTarget,
    RerunSummary,
    RiskFlag,
    RiskFlagDelta,
    RolloutConfig,
    RunArtifactPaths,
    RunConfig,
    RunResult,
    RuntimeItemSignals,
    ScenarioConfig,
    ScenarioContext,
    ScenarioGeneratorMode,
    ScenarioPack,
    ScenarioPackMetadata,
    SessionTrace,
    Slate,
    SlateItem,
    TraceDelta,
    TraceScore,
    TraceStep,
    UtilityBreakdown,
    trace_metric,
)


def audit(**kwargs):
    """Run one audit against a Python callable, class, or class instance."""
    from .api import audit as _audit

    return _audit(**kwargs)


__all__ = [
    "Action",
    "ActionDecision",
    "AdapterRequest",
    "AdapterResponse",
    "AnalysisResult",
    "AgentSeed",
    "AgentState",
    "audit",
    "CohortSummary",
    "DecisionExplanation",
    "FailureMode",
    "FailureModeCount",
    "GeneratedScenario",
    "MetricDelta",
    "MetricSummary",
    "Observation",
    "PopulationGeneratorMode",
    "PopulationPack",
    "PopulationPackMetadata",
    "RankedItem",
    "RankedList",
    "GeneratedPersona",
    "RegressionDiff",
    "RegressionTarget",
    "RiskFlagDelta",
    "RiskFlag",
    "RolloutConfig",
    "RerunSummary",
    "RuntimeItemSignals",
    "RunConfig",
    "RunArtifactPaths",
    "RunResult",
    "ScenarioConfig",
    "ScenarioContext",
    "ScenarioGeneratorMode",
    "ScenarioPack",
    "ScenarioPackMetadata",
    "SessionTrace",
    "Slate",
    "SlateItem",
    "TraceDelta",
    "TraceScore",
    "TraceStep",
    "UtilityBreakdown",
    "build_run_config",
    "execute_domain_audit",
    "generate_population_pack",
    "generate_scenario_pack",
    "get_domain_definition",
    "list_domain_definitions",
    "list_public_domain_definitions",
    "load_population_pack",
    "load_scenario_pack",
    "register_domain_definition",
    "run_domain_regression_audit",
    "run_regression_audit",
    "trace_metric",
]
