"""Public package surface for the first real recommender interaction slice."""

from .audit import run_recommender_audit
from .config import build_default_run_config
from .regression import run_regression_audit
from .scenario_generation import generate_scenario_pack, load_scenario_pack
from .schema import (
    Action,
    ActionDecision,
    AdapterRequest,
    AdapterResponse,
    AgentSeed,
    AgentState,
    AnalysisResult,
    CohortSummary,
    DecisionExplanation,
    FailureMode,
    FailureModeCount,
    GeneratedScenario,
    MetricDelta,
    MetricSummary,
    Observation,
    RegressionDiff,
    RegressionTarget,
    RerunSummary,
    RiskFlag,
    RiskFlagDelta,
    RolloutConfig,
    RunArtifactPaths,
    RunConfig,
    RunResult,
    RuntimeItemSignals,
    ScenarioConfig,
    ScenarioContext,
    ScenarioGeneratorMode,
    ScenarioPack,
    ScenarioPackMetadata,
    SessionTrace,
    Slate,
    SlateItem,
    TargetMode,
    TraceDelta,
    TraceScore,
    TraceStep,
    UtilityBreakdown,
)

__all__ = [
    "Action",
    "ActionDecision",
    "AdapterRequest",
    "AdapterResponse",
    "AnalysisResult",
    "AgentSeed",
    "AgentState",
    "CohortSummary",
    "DecisionExplanation",
    "FailureMode",
    "FailureModeCount",
    "GeneratedScenario",
    "MetricDelta",
    "MetricSummary",
    "Observation",
    "RegressionDiff",
    "RegressionTarget",
    "RiskFlagDelta",
    "RiskFlag",
    "RolloutConfig",
    "RerunSummary",
    "RuntimeItemSignals",
    "RunConfig",
    "RunArtifactPaths",
    "RunResult",
    "ScenarioConfig",
    "ScenarioContext",
    "ScenarioGeneratorMode",
    "ScenarioPack",
    "ScenarioPackMetadata",
    "SessionTrace",
    "Slate",
    "SlateItem",
    "TargetMode",
    "TraceDelta",
    "TraceScore",
    "TraceStep",
    "UtilityBreakdown",
    "build_default_run_config",
    "generate_scenario_pack",
    "load_scenario_pack",
    "run_regression_audit",
    "run_recommender_audit",
]
